### ISSUE TITLE
How to test methods in the component?

### ISSUE THREAD

**Issue by VueBeginner** [testing-library/vue-testing-library#116]
I've seen the testing examples like simple-button.js which has :
 `await fireEvent.click(getByRole('button'))` and tests the emitted() function. 
But how can I actually test the handleClick method  in the Component:
`<button @click="handleClick">{{ text }}</button>`. 
I want to be able to write something like: `expect(handleClick).toHaveBeenCalled()`.  
Or for a component with mounted hook:
`mounted() {
   doSmth(x, y, z)
}` 
`expect(doSmth).toHaveBeenCalledWith(x,y,z)`
I can't find any solution for that problem in the docs  https://testing-library.com/docs/vue-testing-library/api or any other examples here.

**Comment by afontcu** [comment]
Hi! The guiding principle of this library is that you shouldn't be testing specific methods, but rather the "output" of the method.

Is the method emitting an event? Is it sending an HTTP request? those are the things you'd want to test.

If you need further help, feel free to reopen the issue and share your `handleClick` implementation and we can figure out what to test :)
