### ISSUE TITLE
Cannot set data properties on a component

### ISSUE THREAD

**Issue by EvanBurbidge** [testing-library/vue-testing-library#118]
**Describe the bug**
From what i've heard this library is a wrapper around @vue/test-utils, one of the most handy functions I find with that library is the wrapper.setData() method. I cannot do that with this library.

**Expected behavior**

When rendering a component I should be able to set the data attributes on rendering.
```javascript
const { debug } = render(Component, {props: {}, data: { someProperty: 'string' } } );
debug(); // see string in the template etc.
```
**Related information:**

- `@testing-library/vue` version: 4.1.0
- `Vue` version: 2.6.10
- `node` version: 10.16.0
- `npm` (or `yarn`) version: 6.9.0

**Comment by afontcu** [comment]
Hi! Thanks for filling in the issue.

This is not a bug, since VTL aims for providing the tools that allow you to interact with your components as the end user or the developer would do – neither of them would be able to directly modify the internal data from a component, and this is why VTL does not exposed such method.

What's your use case? Maybe we can figure it out 🙌

**Comment by EvanBurbidge** [comment]
@afontcu In my component there are some api calls within methods on the component. These set certain data attributes, i'm not sure how to mock them as they are hardcoded into the component itself. This is why i'm using the setData method from vue-test-utils in order to set the values.

**Comment by afontcu** [comment]
You should mock you API calls – https://afontcu.dev/testing-api-calls/

So you can test without hitting a back end, and also reassure that you're getting the desired output from the API call.

**Comment by EvanBurbidge** [comment]
In that example the api calls are in a separate file. My api calls are written into the vue component itself.

**Comment by afontcu** [comment]
If a test is hard to write, it usually means the component is doing too much, or that it is too coupled. You might benefit from removing responsibilities from it to other parts of your system.

Anyway, you can easily mock `axios` (or `fetch` or any other service) the same way!

**Comment by EvanBurbidge** [comment]
This is true, might refactor the component! Nice one :)

**Comment by afontcu** [comment]
Thanks for commenting, though! :) Feel free to raise any other issue or ask any question in our Spectrum chat: https://spectrum.chat/testing-library
