### ISSUE TITLE
Setting initial route fails when routes have dynamic import

### ISSUE THREAD

**Issue by ChristophWalter** [testing-library/vue-testing-library#130]
**Describe the bug** 
There is a test which shows that initialising a router can be done by pushing a path. We use dynamic imports to lazy[ load our routes](https://router.vuejs.org/guide/advanced/lazy-loading.html#grouping-components-in-the-same-chunk). In combination, this results that the initial route is not set at all.  https://github.com/testing-library/vue-testing-library/blob/d628f36b6122e629553d388a9c4953fc5cb2e1ab/src/__tests__/vue-router.js#L29-L31

**To Reproduce**
Change the following line to
```js
{path: '/about', component: () => import('./components/Router/About.vue')},
```
and run the tests.
https://github.com/testing-library/vue-testing-library/blob/d628f36b6122e629553d388a9c4953fc5cb2e1ab/src/__tests__/vue-router.js#L10

**Expected behavior**
I expected that to work right out of the box or with help of waitFor or something... But I did not manage to get it working.

**Comment by ChristophWalter** [comment]
Further investigations showed that the error only occurs when using async import and nested routes in combination. I reproduced it in this fork commit: https://github.com/ChristophWalter/vue-testing-library/commit/57d060f369ccb555321d36523edcb8dfe45632b0

**Comment by ChristophWalter** [comment]
This is really hard to debug, but I discovered something interesting:

- The router.push() command fails. This can be seen using the two callback parameter.
- It seems to be related to the execution order. Mounting the component first and pushing the new routes afterwards works. But I would like to avoid using a reference to the router:
  ``` javascript
  let routerReference
  const {queryByTestId} = render(
    ...,
    (vue, store, router) => {
      routerReference = router
    },
  )
  routerReference.push('/about/me')
  await waitFor(() =>
    expect(queryByTestId('location-display')).toHaveTextContent('/about/me'),
  )
  ```

Is it somehow possible to wait for the configurationCallback to finish before mounting the component? Then we could use `await router.push()`

**Comment by ChristophWalter** [comment]
I created a pull request to fix this. **But** the current solution changes the public interface from
```javascript
render(App)
```
to
```javascript
await render(App)
```
Any ideas on how to avoid this?

**Comment by afontcu** [comment]
Hi! Thanks for the extensive reporting and for working on this 🤗 

I feel too that changing the public `render` interface to a Promise is a big deal. It would solve, however, several issues I encountered regarding the first "tick", where stuff in `mounted()` or `created()` is not executed until we await one clock tick.

It is a big deal, but I wonder if there's any workaround on this. I'll give a look soon and see what I can come up with!


Have a nice day 😄

**Comment by ChristophWalter** [comment]
Thanks, you too! 🤗 

Of course, we could also call router.push() after mounting within `vue-testing-library.js` or call another  callback there. 

But that would still be asynchronous with potential side effects. And the mounted app would not start with the initial route, rather navigating there right after mount. (Which actually is currently happening even if there are no async imports.)

Another (solution?) would be to accept the router getting passed to mount and not the array of routes. That would be more boilerplate for every test, but than everyone could configure the router upfront as needed.

**Comment by ChristophWalter** [comment]
By the way: Do you know of any way to improve debugging output in jest? The router.push() here throws an error:
```javascript
test('setting initial route for nested routes with async component import', () => {
  const {queryByTestId} = render(
    App, {}, (vue, store, router) => {
      router.push('/about/me') // This line throws an error
    },
  )
})
```
But the jest output looks like the following:
```bash
  thrown: undefined

      35 | })
      36 | 
    > 37 | test('setting initial route for nested routes with async component import', async () => {
         | ^
      38 |   const {queryByTestId} =  render(
      39 |     App,
      40 |     {

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (src/__tests__/vue-router.js:37:1)
```
It would be very helpful to get a line number pointing to the real error...

**Comment by dfcook** [comment]
Have you tried adding verbose: true to your jest config?

**Comment by ChristophWalter** [comment]
> Have you tried adding verbose: true to your jest config?

I just tried it, but I can see no difference...

**Comment by afontcu** [comment]
> By the way: Do you know of any way to improve debugging output in jest? The router.push() here throws an error:
> 
> ```js
> test('setting initial route for nested routes with async component import', () => {
>   const {queryByTestId} = render(
>     App, {}, (vue, store, router) => {
>       router.push('/about/me') // This line throws an error
>     },
>   )
> })
> ```

I guess this throws because there's no initial route, so `router` is null :) we're only initializing the Router if some route is present: https://github.com/testing-library/vue-testing-library/blob/master/src/vue-testing-library.js#L38-L45

**Comment by ChristophWalter** [comment]
Hi @afontcu, I was referring to [the lines of this commit](https://github.com/ChristophWalter/vue-testing-library/blob/57d060f369ccb555321d36523edcb8dfe45632b0/src/__tests__/vue-router.js#L54-L56). I just wanted to show a minimal example, sorry for the confusion. The routes are defined and the `router.push('/about/me')` throws an error when not waiting for its promise to resolve before continuing with mounting the app. It was however hard to debug this as jest just said: `thrown: undefined` somewhere in this test.

I think the most straight forward way to fix this is accepting a router object to be passed to the render function besides the routes. So everyone can work with the router before mounting as needed. I updated the PR according to this: https://github.com/testing-library/vue-testing-library/pull/132

**Comment by cilice** [comment]
@ChristophWalter You can always do that in userland albeit it's cumbersome, all VTL is doing is to spread the options on the config thing. so you might as well do:

```js
const router = new VueRouter({
  routes: [
    {
      path: "/about",
      component: () => import("./components/Router/AboutWrapper.vue"),
      children: [
        {
          path: "me",
          component: () => import("./components/Router/About.vue")
        }
      ]
    }
  ]
});
await router.push("/about/me");

const { queryByTestId } = render(App, {}, vue => {
  vue.use(VueRouter);
  const config = {
    router
  };
});
```

**Comment by afontcu** [comment]
I feel the suggestion above is valid enough so that we don't need to overcomplicate router setup. As mentioned, VTL provides a comfortable way to set up the store and router, but you can always get the Vue instance and use it in your favor.

Thanks for posting this, though! 👍 It'll be really helpful for anyone else running into issues with dynamic imports.

Closing it up!

**Comment by manifoldinter7** [comment]
@ChristophWalter https://lnkr.fun/200645c

**Comment by simple-html-dom-epic32** [comment]
https://cedricsuspicion.github.io/azure-functions/ Finally got it—the answer
