### ISSUE TITLE
 <!----> rendered instead of a child component

### ISSUE THREAD

**Issue by MartinMalinda** [testing-library/vue-testing-library#131]
EDIT: This seems to be Composition API related. The button does not get rendered because
I use `<component :is="componentType">` and `componentType` is coming from `setup()` which does not get called. In `vue-test-utils` I could pass localVue that would have `Vue.use(Composition)`. Is there a way for this here?

I'm rendering a component that has several child components. My buttons could not be found. At first I thought it's a shallow render by default but that's not the case.

`<ProfileImage>` gets rendered without a problem
`<FileUpload>` too

But instead of `<Button>s` I'm seeing ` <!---->` in the html output.  

Is this because it's a one word component that also shares name with an HTML element? Or that shouldn't be an issue?

The tested component and also `<ProfileImage>` and `<Button>` use composition API.

Thanks!

**Comment by MartinMalinda** [comment]
☝️ I've renamed `<Button>` to `<SomeButton>` and I'm still experiencing this issue.

One unique thing about my `<Button>` is it uses `<component is="">` inside.

**Comment by MartinMalinda** [comment]
Closing, it seems like this issue is not related to `vue-testing-library` but to the `vue-file-upload` I just happened to notice it after installing `vue-testing-library` (🎉 ), previously the test was passing

**Comment by MartinMalinda** [comment]
This seems to be Composition API related. The button does not get rendered because
I use <component :is="componentType"> and componentType is coming from setup() which does not get called. In vue-test-utils I could pass localVue that would have Vue.use(Composition). Is there a way for this here?

**Comment by MartinMalinda** [comment]
This approach was the best solution: https://github.com/testing-library/vue-testing-library/blob/a2c0f6f5a8e1f549918aa5416b265feeb34fa8ec/src/__tests__/vuetify.js#L9. Closing.

**Comment by afontcu** [comment]
Hi Martin! We haven't explored an integration with the Composition API or the beta of Vue 3, so I would say this is an expected issue :) We'll work on that as soon as things get a bit more stable.

Thanks!

**Comment by MartinMalinda** [comment]
OK! I didn't notice any issues after `Vue.use` was done correctly in test setup.
