### ISSUE TITLE
Rendering an imported component in slot

### ISSUE THREAD

**Issue by MartinMalinda** [testing-library/vue-testing-library#133]
I'm rendering a component like this:

```ts
 const { baseElement } = render(MyForm, {
      components: { MyInput },
      propsData: {
        onSuccess
      },
      slots: {
        default: `<MyInput label="firstName" name="firstName" />`
      }
    });
```

Unfortunately, I'm still getting

```
 [Vue warn]: Unknown custom element: <MyInput> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

Is there a solution to this? Thanks!

**Comment by afontcu** [comment]
Hi! I don't think this would work even with Vue Test Utils, would it? 🤔 I mean, VTU doesn't allow to provide a `components` key to register additional components.

I guess you can provide a stub (`stubs: ['MyInput'],`)?

**Comment by MartinMalinda** [comment]
> don't think this would work even with Vue Test Utils, would it?

Ohh, That's quite possible. I'm still quite new to Vue.

Maybe I could create a quick wrapper component just for the test purpose and test it with it, I'll report here tomorrow:)

**Comment by afontcu** [comment]
Hi @MartinMalinda! Any chance you could give this a go? 😇

**Comment by MartinMalinda** [comment]
Yes! This approach seems to work:

```ts
function createWrap(onSuccess) {
  return Vue.component('wrapComponent', {
    components: { MyForm, MyInput },
    render(h) {
      return h(MyForm, {
        props: {
          onSuccess
        },
        scopedSlots: {
          default() {
            return h(MyInput, {
              attrs: {
                label: 'firstName',
                name: 'firstName',
                'validation-rules': 'required'
              }
            });
          }
        }
      });
    }
  });
}
```

test:

```ts
 const onSuccess = jest.fn();
 const { baseElement, getByLabelText } = render(createWrap(onSuccess));
```

Afterwards I can test the interaction between both of these components. Still feels a bit like a workaround though. Would be nice to have a JSX at least or better, pass a template. Good enouh for me so far though.
