### ISSUE TITLE
Using external libraries

### ISSUE THREAD

**Issue by jdriesen** [testing-library/vue-testing-library#140]
Hi,

First of all, thanks for sharing this great library.
It's really a great help !

I'm having a small question about using external libraries.
e.g. I would like to use to the ```jest-image-snapshot``` library.

Can you give me a some info about best practices ?
(an small example would be really great...)

Thanks in advance for your reply,

Kind regards,
Johnny Driesen
Belgium

**Comment by afontcu** [comment]
Hi! Thank you for your kind words :)

I've never used this library before, but seems like you just need to pass in some DOM nodes, right? You could get `container` or `baseElement` from `render()`,  and pass it down to `jest-image-snapshot`.

**Comment by jdriesen** [comment]
Thanks for your quick reply, @afontcu .
Gonna give it a try.
(though, I've to say I'm rather new to Vue Testing )

BTW: Thanks for all your documentation !
That's really a great help for a newbie like me.

**Comment by afontcu** [comment]
Thanks! Going to close this up, feel free to ask for help in [Spectrum](http://spectrum.chat/testing-library) and open new issues in the repo for potential bugs or missing features :)

**Comment by jdriesen** [comment]
If I can ask ... 
- any particular reason why you're using ```kdc-scripts``` in your demo ? (confuses me a bit)
- Seems that upgrading ```@vue/test-utils": "^1.0.0-beta.32``` to the latest version (i.e. 1.0.2) breaks everything...

Can you give me a little help, please ?

**Comment by afontcu** [comment]
> any particular reason why you're using `kdc-scripts` in your demo ? (confuses me a bit)

Because Vue Testing Library is part of the [Testing Library](https://testing-library.com/) family, and almost all other projects use `kcd-scripts` as well. This way we can keep things similar across projects.

> Seems that upgrading `@vue/test-utils": "^1.0.0-beta.32` to the latest version (i.e. 1.0.2) breaks everything...

Yep, that's quite expected. We're working on it here: https://github.com/testing-library/vue-testing-library/pull/139

**Comment by jdriesen** [comment]
Once again, thanks for your quick reply.
Thanks to you, I've learned already a lot today.

And I promise, next time,  I'll use Spectrum for my questions.
