### ISSUE TITLE
Feature: Can provide a similar reactRender hook test library for vue？

### ISSUE THREAD

**Issue by xiaoping027** [testing-library/vue-testing-library#157]
Can provide a similar reactRender hook test library for vue？

**Comment by afontcu** [comment]
Hi! I'm not sure what `reactRender` is (I don't think it is part of RTL's API). Can you elaborate, please? Maybe provide a valid use case where current Vue Testing Lib API is not able to solve :)

Thank you!

**Comment by nickmccurdy** [comment]
I think they're referring to testing-library/react-hooks-testing-library.

**Comment by afontcu** [comment]
Hi! 👋 

 Oh, I see, that makes sense. I assume someone might want to test [Composition API](https://v3.vuejs.org/guide/composition-api-introduction.html#standalone-computed-properties) functions in isolation, but that's beyond the scope of Vue Testing Lib (similar to testing hooks, which is out of scope for React Testing Lib). For the time being, though, one can render a component and test its inputs/outputs no matter the paradigm.

I'll go ahead and close this issue as there isn't much to do here :)

**Comment by xiaoping027** [comment]
https://github.com/xiaoping027/vue-renderhook/blob/master/test/index.test.ts
