### ISSUE TITLE
composition-api not support?

### ISSUE THREAD

**Issue by lizy0329** [testing-library/vue-testing-library#159]
**Describe the bug** A clear and concise description of what the bug is.
A Component render error that use composition-api.

return value in Setup function is nothing.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior**
render successfully

**Screenshots**

**Related information:**

- `@testing-library/vue` version: ^5.1.0
- `@vue/composition-api` version: ^1.0.0-beta.14
- `node` version: 10+
- `npm` (or `yarn`) version: 6+

Relevant code or config (if any)

```javascript

```

**Additional context**

**Comment by afontcu** [comment]
Hi!

Could you please post the failing test? Vue Testing Library is using VTU 1.X, meaning it uses Vue 2. So, as long as you register the composition API public, you should be good

```js
import VueCompositionAPI from '@vue/composition-api'

test('composition api', () => {
  render(Component, {}, vue => vue.use(VueCompositionAPI))
})
```

**Comment by lizy0329** [comment]
Thank you for your answer! 
Normal rendering! 
But in TypeScript, I found that need to use `(vue) => {vue.use(VueCompositionAPI)}` instead of `vue => vue.use(VueCompositionAPI)`, if not, throw error.

**Comment by lizy0329** [comment]
There has one question for fireEvent.click() not work.

```javascript
const { getByText } = render(UseClipboardPage, {}, (vue) => {
            vue.use(VueCompositionApi);
        });

        getByText('state: false');

        const copyButton = getByText(/copy/i);
        await fireEvent.click(copyButton);
        // error: state: false
        getByText('state: true');
```

**Comment by afontcu** [comment]
Hi!,

this might be due to the test itself, and it is hard to debug without seeing the test and the component. I might blindly suggest to use `fireEvent.update` instead of `click`.

I'm going to close the issue, since there's nothing that prevents people from using composition API :) feel free to open up additional issues if needed. 


Thanks!
