### ISSUE TITLE
Testing emit from $root

### ISSUE THREAD

**Issue by jskogelin** [testing-library/vue-testing-library#169]
Any recommendations on testing functionality that depends on listening to events emitted via `$root.$emit`? Like you would via `wrapper.vm.$root.$emit` for example using `vue-test-utils`. Haven't been able to find anything in the docs. 

Thanks for a great library!

**Comment by afontcu** [comment]
Hi! Can you share a component/test example?

**Comment by jskogelin** [comment]
Sure! The `created` hook of the component I would like to test looks something like this:
```javascript
export default {
  name: 'ComponentToTest',
  created () {
    this.$root.$on('event', () => {
      // This runs an axios request and conditionally displays a component based on the response
      this.fetchFromServerAndDisplayElement()
    })
  }
  ...
}
```
Template of `ComponentToTest`
```html
<template>
  <component-to-display v-if="requestReturnedTrue">
    displayThis
  </component-to-display>
</template>
```

Then, in my test
```javascript
it('should display a component on root emit', function () {
  const { getByText } = render(ComponentToTest, ...)
  
  // Here I somehow want to test that the component responds to the event
  // emitted via $root.$emit

  expect(getByText('displayThis')).toBeInTheDocument()
})
```

**Comment by afontcu** [comment]
Hi! Vue Testing Library offers a third parameter which gives you access to the vue instance (https://github.com/testing-library/vue-testing-library/blob/master/src/vue-testing-library.js#L51-L53):

```js
render(Component, {}, vue => {})
```

maybe you can leverage it to trigger the event? let me know how it goes!

**Comment by jskogelin** [comment]
Been digging through the instance and haven't been able to find anything that helps me trigger the event unfortunately.

I've also attempted to mock `$root` by setting it to a Vue instance i have access to, but no luck.

**Comment by jskogelin** [comment]
Let me know if this is a feature the library needs and I'll send in a PR!

**Comment by jueinin** [comment]
need to get the vue instance object too! in some special environmens, I need to mock some methods on vm

**Comment by lmiller1990** [comment]
Can you just wrap the component?

```js
const Wrapper = (comp) => {
  return {
    render: (h) => h('div', h(comp))
}
```

Now you can do `mount(Wrapper)` and since `Wrapper` is the `$root`, you should be able to do see the emitted events on it. Note: I have not tried this and it might not work at all.

I also noticed `$on` no longer exists in Vue 3, you might want to keep this in mind.

**Comment by jskogelin** [comment]
> Can you just wrap the component?

Thank you! Can't believe I didn't think of this sooner. This was my solution:

```javascript
it('should respond to root emit', function () {
    const Wrapper = {
      mounted () {
        this.$root.$emit('emit-to-test')
      },

      render (h) {
        return h('div', [ h(ComponentToTest) ])
      }
    }

    // ...assert stuff
})
```

> I also noticed $on no longer exists in Vue 3, you might want to keep this in mind.

Thanks for the heads up!

**Comment by Thaval** [comment]
@jskogelin Why do you use "it", shouldn't you use "test" with this vue testing library? Seems like you use another library called "vue-test-utils" which is the low-level api of this library. Correct me if I'm wrong...

However, I'm facing the same problem. My component initializes its data by listening on an event. How can I initialize my data from within a test?

Within the created function:
```
 created() {
            this.$root.$on(EventNames.myEvent, (data: dataType[]) => {
                this.myData= data
            })
        }
```

Now in the test (how can I initialize the MyComponent so that the $root.$on is triggered?):
```
test('increments value on click', async () => {
    // The render method returns a collection of utilities to query your component.
    const { getByText, queryAllByTestId,  } = render(MyComponent, {
        props: {

        },
        
    })
}
```
