### ISSUE TITLE
Invitation to move to testing-library org

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/vue-testing-library#17]
It's up to you, but if you'd like, you're welcome to transfer this repository to the [testing-library organization on GitHub](https://github.com/testing-library). This will give your project more credibility as part of the testing-library family of projects with a unified mission of tools which help people avoid testing implementation details.

Again, totally up to you. I just want you to know we appreciate all you've done and you're welcome to join us if you like.

**Comment by dfcook** [comment]
Happy to do this, how do I proceed?

**Comment by kentcdodds** [comment]
I've added you to the org. Accept that invitation here: https://github.com/testing-library then go to the settings of the vue-testing-library repository and click "Transfer"

Let me know when that's done and I'll get the repo added to the Vue team (of which you're a member). You should be able to manage the repo the same as you always have :)

**Comment by dfcook** [comment]
Done and done.
