### ISSUE TITLE
Module '"../node_modules/@testing-library/vue/types"' has no exported member 'cleanup'.ts(2305)

### ISSUE THREAD

**Issue by ryotah** [testing-library/vue-testing-library#184]
**Describe the bug**

`cleanup` function doesn't exist in [`types/index.d.ts`](https://github.com/testing-library/vue-testing-library/blob/v5.5.0/types/index.d.ts) now, so we cannot load `cleanup` function from TypeScript files.

Probably we need to add `export function cleanup(): void;` like [`DefinitelyTyped/types/testing-library__vue/index.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8e7a71356a0bdb45a15261b4219ae9b34724562e/types/testing-library__vue/index.d.ts#L15)

**Screenshots**

<img width="821" alt="cleanup" src="https://user-images.githubusercontent.com/1491961/100049616-2013c400-2e5b-11eb-82cc-82970f1ec719.png">

**Related information:**

- `@testing-library/vue` version: v5.5.0
- `node` version: v14.7.0
- `npm` (or `yarn`) version: v6.14.7

**Comment by afontcu** [comment]
yep, that's true! Fancy to open up a PR? :)

**Comment by MatanBobi** [comment]
@afontcu I can take care of this one in https://github.com/testing-library/vue-testing-library/pull/185 also if you want..

**Comment by briankoehler** [comment]
I'm noticing that the `next` channel is still experiencing this issue. It would probably be resolved by adding `export function cleanup(): void` to that branch's [`index.d.ts`](https://github.com/testing-library/vue-testing-library/blob/next/types/index.d.ts) as well, right?

**Comment by MatanBobi** [comment]
@briankoehler that's true.. Wan't to open a PR for that or I'll fix that? :)
