### ISSUE TITLE
this.$router is undefined

### ISSUE THREAD

**Issue by horaciosystem** [testing-library/vue-testing-library#19]
# 🐞 bug report

### Description

Tests are failing when a component uses router instance to redirect.
The component does call a callback that makes a redirect programmatically.
 
```js
 onSuccess() {      
   this.$router.push('/')
 }
```

## 🔥 Exception or Error
<pre><code>
TypeError: Cannot read property 'push' of undefined
</code></pre>

## 🌍  Your Environment

<pre><code>
    "jest": "^24.7.1",
    "jest-dom": "^3.1.4",
    "jest-mock-axios": "^3.0.0",
    "vue-jest": "^3.0.4",
    "vue-template-compiler": "^2.5.21",
    "vue-testing-library": "^0.16.0"
</code></pre>

**Comment by dfcook** [comment]
Can you create a small sandbox test?

**Comment by dfcook** [comment]
Added an example test that uses programmatic routing
