### ISSUE TITLE
[Vue 3 Support] Incorrect type definitions in latest release

### ISSUE THREAD

**Issue by heywhy** [testing-library/vue-testing-library#193]
**Describe the bug** A clear and concise description of what the bug is.

The included type definition (`types/index.d.ts`) for Vue 3 support is missing the **routes** property in the render options, this fails because the tests are written in a **.ts** file.

**To Reproduce**

* Install `@testing-library/vue@next` and confirm the content of the **node_modules/@testing-library/vue/types/index.d.ts**

**Expected behavior**

* I expect the declaration to contain the **routes** property as is in the **next** branch.

**Screenshots**

<img width="1433" alt="Screen Shot 2020-12-13 at 11 55 03 PM" src="https://user-images.githubusercontent.com/13123868/102026541-bffba800-3d9e-11eb-911c-61ab0b498728.png">

<img width="1361" alt="Screen Shot 2020-12-13 at 11 55 41 PM" src="https://user-images.githubusercontent.com/13123868/102026546-c4c05c00-3d9e-11eb-9005-93178ebdc8f9.png">

**Related information:**

- `@testing-library/vue` version: ^6.3.0
- `Vue` version: ^3.0.4
- `node` version: 12.16.2
- `npm` (or `yarn`) version: 1.22.5

**Additional context**

The problem is the current release on npm which doesn't contain an up-to-date declaration file.

**Comment by afontcu** [comment]
Hi! This commit https://github.com/testing-library/vue-testing-library/commit/05275b91e801e11c3ee294d31ac43ac634021ca2 should've issued a release with proper types, but looks like CI failed due to some caching issue. Let me see if I can get it working now.

**Comment by afontcu** [comment]
okay, fixed! 6.3.1 should come now with right types for Router :) https://github.com/testing-library/vue-testing-library/releases/tag/v6.3.1

Closing this up, feel free to open up a new issue if something comes up! 

Thanks 🚀
