### ISSUE TITLE
Unexpected parameter format for rerender() - v6 (next)

### ISSUE THREAD

**Issue by mammadataei** [testing-library/vue-testing-library#197]
Hi,
The rerender function's signature on v6 is: 
```ts
rerender(props: object): Promise<void>
```
But this is how it works:
```ts
rerender({ props: { error: false } })
```
I think the `props` key is redundant and misleading here and it needs to be something like:
```ts
rerender({ error: false })
```

**Comment by afontcu** [comment]
Hey! Yeah, I agree that it looks weird and that `rerender({ error: false })` makes more sense.

However, at some point we might need to add other keys (we're "rerendering", after all, not only setting new props), which would then mean introducing a breaking change.

That being said, `rerender` should not be used that much (people should rather write a new test), so I guess it's OK only letting props be there.

Fancy to open up a PR (against `next` branch)? 🙌

**Comment by afontcu** [comment]
I wonder if we could cleanup (no pun intended) the `rerender` function a bit:

```js
    rerender: ({props}) => {
      cleanup()
      render(Component, {props})
    },
```

this would allow us to simply pass all options (props and whatnot)

```js
    rerender: (renderOptions) => {
      cleanup()
      render(Component, renderOptions)
    },
```

Then, setting `{ props }` would make sense, becuse it is the same API as when you render the component initially
