### ISSUE TITLE
Quick question: Does this support <script lang="ts">?

### ISSUE THREAD

**Issue by JoeSchr** [testing-library/vue-testing-library#204]
If yes, do I need to install an additional compiler or bundler for that? I'm using Nuxt, just for completeness sake

**Comment by afontcu** [comment]
Hi,

Vue Testing Lib is only a wrapper on top of Vue Test Utils – that is, it leverages whatever testing config you use. If your setup allows you to parse&test TS-based components (that is, using vue-jest and ts-jest and whatnot), then Vue Testing Library should work just fine 👍

**Comment by JoeSchr** [comment]
Thank you!
On Fri, 29 Jan 2021 11:43:57 +0100, "Adrià Fontcuberta"
<notifications@github.com> said:
