### ISSUE TITLE
Is there a better way of handling v-model?

### ISSUE THREAD

**Issue by afontcu** [testing-library/vue-testing-library#22]
Hi! I know that #16 has been closed and that there's an answer to the original question, but I was wondering if there's any advance in the idea of a `fireEvent.update` method.

I guess it'd make sense to come up with a way of handling input data consistently, without depending on `v-model` being there... am I right? For that to happen, should the issue mentioned [here](https://github.com/testing-library/vue-testing-library/blob/master/tests/__tests__/form.js#L13) be fixed? By the way, is there an open issue in the official library repo? Failed to find any reference.

Thanks, and thank you for your work with this library. Testing is pleasant again.

**Comment by dfcook** [comment]
Finally got around to looking at this, PR raised.

Assuming this goes in, should updateState be removed?

**Comment by afontcu** [comment]
> Assuming this goes in, should updateState be removed?

Makes sense! It is quite pointless now, isn't it? Its only purpose AFAIK was to make v-model work.

**Comment by dfcook** [comment]
Fixed in #34
