### ISSUE TITLE
Vue-i18n example test does not exist and has a dead link

### ISSUE THREAD

**Issue by ericbednarz** [testing-library/vue-testing-library#222]
**Describe the bug**

The project [README](https://github.com/testing-library/vue-testing-library#more-examples) contains a link to a vue-i18n example test that does not exist.

**To Reproduce**

Activate the link and observe a [404 resonse](https://github.com/testing-library/vue-testing-library/blob/master/src/__tests__/vue-i18n.js).

**Expected behavior**

There is either a resource or no link.

**Comment by ericbednarz** [comment]
The same dead example link is also referenced in the documentation of the callback function parameter of the render function: https://testing-library.com/docs/vue-testing-library/api#callback-function

**Comment by afontcu** [comment]
Hi! You're right, the correct link is https://github.com/testing-library/vue-testing-library/blob/master/src/__tests__/translations-vue-i18n.js

Fancy to open up a PR fixing either the filename or the links?

**Comment by ericbednarz** [comment]
Sorry, I was busy. However, I just saw that https://testing-library.com/docs/vue-testing-library/api#callback-function links to a file including the translations- prefix. :-(

**Comment by ericbednarz** [comment]
Right, hat was yesterday. https://github.com/testing-library/testing-library-docs/commit/376a8f2f5166b4a78a22215e7314aa8eb28c40d5
 
Removing the prefix seemed simpler (2 fixes with one change) and more consistent with other test file names. Gonna update the PR then.
