### ISSUE TITLE
VTL for Vue 3: expose the RenderOptions type

### ISSUE THREAD

**Issue by sand4rt** [testing-library/vue-testing-library#224]
I would like the RenderOptios type to be exposed so i can create a typed `DeepPartial<RenderOptios>` prop on my factory function. Example: [https://lmiller1990.github.io/vue-testing-handbook/components-with-props.html#refactor-with-a-factory-function](https://lmiller1990.github.io/vue-testing-handbook/components-with-props.html#refactor-with-a-factory-function
)

index.d.ts, line 45:
```TypeScript
export type RenderOptions = VueTestingLibraryRenderOptions &
  VueTestUtilsRenderOptions
```

**Comment by afontcu** [comment]
Hi! Sure, looks like a sensible request. Fancy to open up a PR?

**Comment by sand4rt** [comment]
Awesome! Yeah sure i'll create a PR

**Comment by sand4rt** [comment]
@afontcu I cant push my branch:

remote: Permission to testing-library/vue-testing-library.git denied to sand4rt.
fatal: unable to access 'https://github.com/testing-library/vue-testing-library.git/': The requested URL returned error: 403

**Comment by afontcu** [comment]
Hi! you might need to fork the repo and submit a PR from repository to repository, instead of branch to branch
