### ISSUE TITLE
Vue 3: typed TestComponent on render function

### ISSUE THREAD

**Issue by sand4rt** [testing-library/vue-testing-library#228]
Proposal: 

Change line 45 index.d.ts from:
```TypeScript 
export function render(
  TestComponent: any, // this makes me sad :sob:
  options?: RenderOptions,
): RenderResult
```

To:
```TypeScript 
export function render(
  TestComponent: new () => ComponentPublicInstance,
  options?: RenderOptions,
): RenderResult
```

**Comment by afontcu** [comment]
Will this handle all Component signatures? If I recall correctly, we had a hard time doing this in the official Vue Test Utils for Vue 3 – Check this out: https://github.com/vuejs/vue-test-utils-next/blob/master/src/mount.ts

**Comment by sand4rt** [comment]
Probably not if i look at the VTU implementation. I guess this ticket can be closed.
