### ISSUE TITLE
Type errors with TypeScript 3.9.7

### ISSUE THREAD

**Issue by blimmer** [testing-library/vue-testing-library#240]
**Describe the bug** `tsc` compile fails with Typescript v3.9.7

**To Reproduce** Steps to reproduce the behavior:

See https://github.com/blimmer/vue-testing-library-issue / https://github.com/blimmer/vue-testing-library-issue/runs/2946243182?check_suite_focus=true

**Expected behavior**

The Typescript compile should pass with TypeScript v3.

**Screenshots**

![Screen Shot 2021-06-29 at 2 31 48 PM](https://user-images.githubusercontent.com/630449/123863365-becb3c00-d8e6-11eb-9fbb-ca8e93f1542c.png)

**Related information:**

- `@testing-library/vue` version: 5.8.0
- `Vue` version: N/A
- `node` version: 14
- `npm` (or `yarn`) version: N/A

Relevant code or config (if any)

```javascript
import '@testing-library/vue'
```

**Additional context**

Shouldn't the TypeScript check step of the CI system catch this?

**Comment by nickmccurdy** [comment]
> Shouldn't the TypeScript check step of the CI system catch this?

See #189
