### ISSUE TITLE
provide , inject feature

### ISSUE THREAD

**Issue by navidshad** [testing-library/vue-testing-library#254]
HI everyone
is there any way to test provide/inject feature of vue components in vue-testing-component?

**Comment by sand4rt** [comment]
Hi @navidshad, yes there is. The provide object is re-exposed from the [vue-test-utils library](https://next.vue-test-utils.vuejs.org/api/#global-provide). You can use it like the code below:

```JavaScript
render({
  global: {
    provide: {
        ...
    }
  }
})
```

**Comment by navidshad** [comment]
oh amazing, I use typescript but this parameter is not in types

**Comment by sand4rt** [comment]
I also use TypeScript myself and i see that the paramater is typed. Note that `provide` is wrapped with `global`.

**Comment by slacktracer** [comment]
Is this somewhere in the docs? I tried to use it as Vue Test Utils docs say it is used and they say nothing about wrapping in this global property object... 🤔
