### ISSUE TITLE
need to help about dynamic routing test

### ISSUE THREAD

**Issue by sevkioruc** [testing-library/vue-testing-library#256]
Hello everyone,

I want to test that clicking item after route to detail page of the item.

Although I looked previous issues about this topic I could not solve problem.

I am using  Vue 2, Jest and vue-testing-library
and I mocked backend with https://github.com/mswjs/msw

- TodoList.spec.js
```js
import TodoList from '../src/components/TodoList.vue'
import TodoDetail from '../src/components/TodoDetail.vue'
```

```js
const routes = [
    { path: '/', component: TodoList },
    { path: '/todo/:id', component: TodoDetail }
]
```
```js
it('route to detail page of todo after clicking on todo', async () => {
     render(TodoList, { routes })

     const todo = await screen.findByText('Todo1')
     await userEvent.click(todo)

     const detailPage = await screen.findByTestId('detail-page')
     await waitFor(() => { expect(detailPage).toBeInTheDocument() }, { timeout: 10000 })
})
```
- TodoList.vue
```vue
        <li class="list-group-item" v-for="(todo, index) in todos" :key="index">
          <p class="card-text">
            <router-link :to="'/todo/' + todo.id">
              {{ todo.title }}
            </router-link>
          </p>
        </li>
```

**Comment by afontcu** [comment]
Hi!

You're rendering `TodoList`, not the whole app (with `<router-view>` and so on). If you want to test a whole router interaction, please check out https://github.com/testing-library/vue-testing-library/blob/main/src/__tests__/vue-router.js#L15 as example. Notice that `App.vue` is the root component of the app, not one of its routes.

Hope it helps!

**Comment by sevkioruc** [comment]
Hi!

I understood better more then before and will review this example.
Thank you so much for your answer.
