### ISSUE TITLE
Syntax in vue-router example appears deprecated?

### ISSUE THREAD

**Issue by FlorentBuissonOReilly** [testing-library/vue-testing-library#258]
**Describe the bug** A clear and concise description of what the bug is.

The [vue-router.js file](https://github.com/testing-library/vue-testing-library/blob/main/src/__tests__/vue-router.js) has the following code on line 17:
const {getByTestId} = render(App, {routes})

When I use the syntax render(xxx, {routes}) in my project, I get the following warning: 
 _Providing 'store' or 'routes' options is no longer available.
 You need to create a router/vuex instance and provide it through 'global.plugins'.
 Check out the test examples on GitHub for further details._

However, the test examples in the vue-router.js file do not show the 'global.plugins' approach.

This is my first bug report, I hope it's helpful!

**Comment by afontcu** [comment]
Hi, and thank you for your first report! It seems that you're using Vue Testing Library for Vue 3 (which [lives in `next`](https://github.com/testing-library/vue-testing-library/tree/next)), but checking docs for Vue 2 (which lives in `main`).

Here's the router example file for Vue 3: https://github.com/testing-library/vue-testing-library/blob/next/src/__tests__/vue-router.js

hope it helps!

**Comment by FlorentBuissonOReilly** [comment]
Duh! Yes, you're correct. Thanks for taking the time to let me know!
