### ISSUE TITLE
`render` requires projects to add `vuex` as a dependency

### ISSUE THREAD

**Issue by adam-gipril** [testing-library/vue-testing-library#259]
## Description

This project lists [`vuex` as a dev dependency](https://github.com/testing-library/vue-testing-library/blob/a620424be19e3158b89b575b7603aa7ab5d9f9ec/package.json#L79), but then [the implementation of `render` requires `vuex`](https://github.com/testing-library/vue-testing-library/blob/a620424be19e3158b89b575b7603aa7ab5d9f9ec/src/render.js#L31). As a result, consuming projects that may not use `vuex` in their project code need to add it as a dev dependency to use `render` in the test environment.

## Steps to reproduce

- Create a Vue project and add `@testing-library/vue`, or add `@testing-library/vue` to an existing project.
- Ensure `vuex` is not a dependency in the project.
- Try to write a test with `render`.
- Observe the tests failing because Node can't find `vuex`.

## Expected behavior

I'd expect `vuex` to be a dependency and not a dev dependency of this project as one of its key exports requires `vuex`.

## Related information

- `@testing-library/vue` version: `5.8.2`
- `Vue` version: `>= 2.6.11 < 3`
- `node` version: `12.22.7`
- `npm` (or `yarn`) version: `npm 6.14.15`

**Comment by afontcu** [comment]
Hi! Just gave it a go locally, and Vuex isn't required (and thus nothing fails) unless a `store` option is passed, as expected. The minute I add a `store: {}` option, then I get the error "Cannot find module 'vuex' from 'render.js'". Is it possible that your tests are setting a store?

**Comment by adam-gipril** [comment]
@afontcu I don't believe any of our tests are setting a store. For additional context, the test suites with which I'm working are for a component library. All our current tests are using `@vue/test-utils` directly, and I'm not seeing any of those using a store option either.

The only suite that uses the testing library in our project is the following very simple one below. We're currently using Mocha, and plan to swap over to Jest soon.

```typescript
import { render } from '@testing-library/vue';
import { PCard } from '@/components/PCard';

describe('PCard', () => {
  it('renders slotted-in content', () => {
    render(PCard, { slots: { default: 'Hello world' } }).getByText('Hello world');
  });
});

```

**Comment by afontcu** [comment]
Hi @adam-gipril! Thanks for the update. I'll take a look soon and ping you back

**Comment by afontcu** [comment]
@adam-gipril could you provide a small reproduction link – with your mocha setup? I can't find a way to reproduce it in several codebases, and now I'm starting to think it has to do with the test runner somehow

**Comment by adam-gipril** [comment]
@afontcu I'll get you something and ping again. Might not be today — the repo in question is private, and I'll see if I can create a similar testing setup in a small public repo.

**Comment by afontcu** [comment]
Hi @adam-gipril – and happy new year! Could you check if this had something to do with the test runner?
