### ISSUE TITLE
render function has only two parameters: configurationCb is missing 😱 

### ISSUE THREAD

**Issue by vfportero** [testing-library/vue-testing-library#269]
**Describe the bug** A clear and concise description of what the bug is.

I'm following the vue i18n example (https://github.com/testing-library/vue-testing-library/blob/main/src/__tests__/translations-vue-i18n.js) but the exported render function doesn't have the callback parameter to setup the vue i18n plugin.

As seen in the `index.d.ts`, the method function has only two parameters but the documentations says that must have three.

**To Reproduce** Steps to reproduce the behavior:

Just try to follow the vue-118n example with the version 6.5.1 of testing-library/vue

**Expected behavior**

Can pass a third parameter on the `render` function to setup vue 3 plugins to the mounted component.

**Screenshots**

![image](https://user-images.githubusercontent.com/1107782/167246613-61430fca-9973-4a35-b605-146dceaa358a.png)
![image](https://user-images.githubusercontent.com/1107782/167246672-8bf82ed1-d5a8-4b02-91c8-056d935d4e01.png)

**Related information:**

- `@testing-library/vue` version: 6.5.1
- `Vue` version: 3.2.33
- `node` version: 14.18.2
- `npm` version: 6.14.15

**Comment by afontcu** [comment]
Hi!

you're using Vue 3, but following the example for Vue 2. Code for Vue 3 lives in `next` branch, so this is the appropriate vue-i18n example:  https://github.com/testing-library/vue-testing-library/blob/next/src/__tests__/vue-i18n.

**Comment by vfportero** [comment]
Ok, thanks @afontcu, i will try that way.

(the given url is missing the extension part. This is the correct one: https://github.com/testing-library/vue-testing-library/blob/next/src/__tests__/vue-i18n.js)

> Hi!
> 
> you're using Vue 3, but following the example for Vue 2. Code for Vue 3 lives in `next` branch, so this is the appropriate vue-i18n example: https://github.com/testing-library/vue-testing-library/blob/next/src/__tests__/vue-i18n.
