### ISSUE TITLE
Provide a cleanup-after-each file?

### ISSUE THREAD

**Issue by afontcu** [testing-library/vue-testing-library#27]
Hi! `react-testing-library` is providing a [cleanup-after-each](https://github.com/testing-library/react-testing-library/blob/master/cleanup-after-each.js) file that comes in handy to avoid repeating `afterEach(cleanup)` on every test file. They even load it using a setup file, so you load it once and forget about dirty DOM nodes once for all.

Would it make sense to port this feature to vue-testing-library? If so, I'd happily submit a PR with both the file and the required documentation 🤗 

👋

**Comment by dfcook** [comment]
Would appreciate thoughts on the PR for this

**Comment by afontcu** [comment]
Done! 🎉

**Comment by dfcook** [comment]
Released in 1.0.1
