### ISSUE TITLE
`@vue/compiler-sfc` peer dependency warning

### ISSUE THREAD

**Issue by edumudu** [testing-library/vue-testing-library#272]
**Describe the bug** 
When installing `@testing-library/vue` in a project with `vue@3.2.13+` and no `@vue/compiler-sfc` a warning of missing `@vue/compiler-sfc` peer dependencies is shown

**To Reproduce** Steps to reproduce the behavior:
- Install the `@testing-library/vue` in a project with `vue@3.2.13+` and no `@vue/compiler-sfc`

You can view the warning in the terminal on [Codesandbox](https://codesandbox.io/s/i92kyh)

**Expected behavior**

Is expected to not show any warning about peer deps

**Related information:**

- `@testing-library/vue` version: 6.6.0
- `Vue` version: 3.2.37
- `node` version: 16.14.0
- `npm` (or `yarn`) version: pnpm@7.3.0

**Additional context**

As of `vue@3.2.13+` the package `@vue/compiler-sfc` is included in the `vue` and can be accessed as `vue/compiler-sfc`. So is not needed anymore to install it separately, but currently, this project set it as a peer dependency and doesn't seem to use it directly

More info in the package [README](https://github.com/vuejs/core/tree/main/packages/compiler-sfc#readme) 

I'm opening this issue to know if I am missing something, if it's alright I would be happy to open a PR if needed

**Comment by zhanglolo** [comment]
`vue@2.7.0+` also include `@vue/compiler-sfc`.

**Comment by davidysoards** [comment]
+1 OP offered to open a PR, that would be nice.
