### ISSUE TITLE
Is there a reason why the return type of render is not HTMLElement?

### ISSUE THREAD

**Issue by sunecosuri** [testing-library/vue-testing-library#274]
The following lines.
https://github.com/testing-library/vue-testing-library/blob/main/types/index.d.ts#L21-L22

I thought it would be more convenient to same as arguments like  `findBy~~~` in query the  HTMLElement type.
https://github.com/testing-library/dom-testing-library/blob/main/types/queries.d.ts#L63

Is there any reason?

**Comment by afontcu** [comment]
Hi! The main reason is that `HTMLElement` does not include SVG elements: https://github.com/testing-library/react-testing-library/pull/833

thank you for the question!
