### ISSUE TITLE
Unable to make mocking or stubs

### ISSUE THREAD

**Issue by juancampuzano** [testing-library/vue-testing-library#291]
## If I can't use shallow rendering, how do I mock out components in tests?

In the [documentation](https://testing-library.com/docs/vue-testing-library/faq) there is a way to mock a feature, but this is only working in the following library: [@testing-library/jest-dom](https://github.com/testing-library/vue-testing-library/blob/main/src/__tests__/stubs.js)

![image](https://user-images.githubusercontent.com/52759609/211297448-78e79bcc-7e6c-4239-a30d-7f86f117deae.png)

In the [example](https://github.com/testing-library/vue-testing-library/blob/main/src/__tests__/stubs.js) you will see that it is importing the `@testing-library/jest-dom` library on line [#2](https://github.com/testing-library/vue-testing-library/blob/6dd48477002760262652dd047de0897762bd60c4/src/__tests__/stubs.js#L2) instead using `@testing-library/vue`

Do I need to install that library to make the mocking? Or Is there a way to do it in the `@testing-library/vue` library?

**Comment by juancampuzano** [comment]
I found the error in the documentation you haven't the **stubs** property inside the **global** property

``` js
import {render} from '@testing-library/vue'
import Component from './Component'

test('Can stub components', () => {
  render(Component, {
     global: { stubs: ['FontAwesomeIcon'] },
  })
})
```

**Comment by jasosims** [comment]
@juancampuzano Thanks! I was stuck on this for quite awhile because the documentation is incorrect.

**Comment by afontcu** [comment]
nice catch! fancy to open up a PR in https://github.com/testing-library/testing-library-docs/blob/main/docs/vue-testing-library/faq.mdx fixing the issue?
