### ISSUE TITLE
Doesn't cleanup with vitest by default

### ISSUE THREAD

**Issue by Maxim-Mazurok** [testing-library/vue-testing-library#296]
**Describe the bug** A clear and concise description of what the bug is.

Since [automatically clean up aftereach](https://github.com/testing-library/vue-testing-library/pull/80) was implemented, `vitest` doesn't run the cleanup by default, leaving previously mounted components to be accessed by later tests.

**To Reproduce** Steps to reproduce the behavior:

`npm init vue@latest` + vitest + vue-testing-library, refer to screenshot below for code (basically just two tests and last one should fail to get element)

**Expected behavior**

It's expected that DOM is cleared up automatically after each test without any custom configuration needed, or the [setup guide](https://testing-library.com/docs/vue-testing-library/setup) is updated

**Screenshots**

![image](https://user-images.githubusercontent.com/7756211/217714531-454ea383-f3c1-4c89-ae74-015859cd55ee.png)

**Related information:**

- `@testing-library/vue` version: 6.6.1
- `Vue` version: 3.2.45
- `node` version: v16.13.0
- `npm` (or `yarn`) version: 8.1.0

Relevant code or config (if any)

```javascript
import { describe, expect, it } from "vitest";

import { render } from "@testing-library/vue";
import HelloWorld from "../HelloWorld.vue";

describe("HelloWorld", () => {
  it("renders properly", () => {
    const { getByText } = render(HelloWorld, {
      props: { msg: "Hello Vitest" },
    });
    expect(getByText("Hello Vitest"));
  });

  it("renders properly again", () => {
    const { getByText } = render(HelloWorld, {
      props: { msg: "Hello Vitest" },
    });
    expect(getByText("Hello Who?"));
  });
});

```

**Additional context**

This is because this library expect `afterEach` to be globally defined, which is not the case with `vitest` by default.
So adding this to vite config fixes the issue:
```
test: {
  globals: true
}
```

**Comment by lmiller1990** [comment]
Thanks for sharing this fix!

**Comment by hypeJunction** [comment]
Is there any alternative? Using globals IMO is a an antipattern and, given that we have many testing libraries around, it makes sense to use explicit imports. Any way to bootstrap testing library without allowing globals?

**Comment by Maxim-Mazurok** [comment]
I personally like to use globals, though on smaller projects don't take time to set them up, and most tests are fine... But yeah, it's not ideal.

Anyway, as mentioned in the [docs](https://testing-library.com/docs/vue-testing-library/api#cleanup) the alternative is to call `cleanup()` after each test. This is what VTL does:
```js
afterEach(() => {
  cleanup()
})
```
In here: https://github.com/testing-library/vue-testing-library/blob/main/src/index.js#L7-L11

You could create some helper method that you'll have to remember to call in all your tests, maybe create a custom eslint rule to remind you about it...

If that sounds like a lot of work and you are still feeling very strongly about not using globals - you can try to patch VTL using something like [`patch-package`](https://www.npmjs.com/package/patch-package) and try to import `afterAll` from `vitest` or whatever you're using. I think it should resolve fine, as long as you have it installed in your project or globally.

It could actually be an interesting PR, try importing from different popular testing frameworks if available. Or maybe somehow try to figure out which framework is currently running... That's an interesting idea, but also quite a bit of work, compared to just enabling globals...

**Comment by dmadridy** [comment]
Is there a workaround to the ts error it shows up after adding this?

`Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'.ts
`

To answer my own question:
You need to place this at the very top of vite.config file

`/// <reference types="vitest/config" />
`
