### ISSUE TITLE
Passing data to a component using the composition api

### ISSUE THREAD

**Issue by Jefry16** [testing-library/vue-testing-library#300]
When unit testing a component that uses the options API I could pass options like this:
```
render(Component, {
      data() {
        return { title: "buzzfeed" }
      },
    })
```

Now that I use the composition API I dont have the option, I mean, the option is there but it does not change in the template as before. What is the way to do it now?

**Comment by afontcu** [comment]
Hi!

Vue Testing Library exists to make these kind of tests (passing arbitrary data to a component) irrelevant, and instead focusing on interacting with a component as a user would: https://github.com/testing-library/vue-testing-library#guiding-principles

with that in mind, the fact that the composition API does not allow to pass in this kind of data is a feature for this library, not a bug.

Thanks!
