### ISSUE TITLE
Type safe render options (props, slots, emits)

### ISSUE THREAD

**Issue by sand4rt** [testing-library/vue-testing-library#305]
Vue released a library _(https://www.npmjs.com/package/vue-component-type-helpers)_ with some type helpers like `ComponentProps<typeof Component>`, `ComponentSlots<typeof Component>` and `ComponentEmits<typeof Component>` which could make the render options type safe.

VTU also recently integrated this library: https://github.com/vuejs/test-utils/blob/main/test-dts/mount.d-test.ts#L60. 

related to: https://github.com/testing-library/vue-testing-library/issues/228 and https://github.com/microsoft/playwright/pull/23151

**Comment by afontcu** [comment]
Fixed in #314
