### ISSUE TITLE
8.0.0 makes it impossible to run with vitest and no global afterEach

### ISSUE THREAD

**Issue by kalvenschraut** [testing-library/vue-testing-library#308]
It is impossible to skip [this](https://github.com/testing-library/vue-testing-library/blob/main/src/index.js#L7)  line of code due to incorrect logic. If afterEach is not defined globally, if statement is false then you will ALWAYS hit the else if check if using vitest irrelevant if you set VTL_SKIP_AUTO_CLEANUP to true.

VTL_SKIP_AUTO_CLEANUP should be moved to the else if and only enter it if not set  to a true value.

**Comment by afontcu** [comment]
If I understand you correctly (the file linked changed, so I'm not 100% sure what line you were talking about), this was addressed in https://github.com/testing-library/vue-testing-library/releases/tag/v8.0.1, as we no longer throw on using VTL wihtout globals (eg when using vitest).
