### ISSUE TITLE
Where should docs live?

### ISSUE THREAD

**Issue by afontcu** [testing-library/vue-testing-library#33]
Hi! So, right now, there are two similar (but no exactly equal) versions of Vue Testing Library docs: in the `README` of this repo, and also in `https://testing-library.com/vue`.

Kent suggested [here](https://github.com/testing-library/testing-library-docs/pull/120) to keep the docs in the official website, and just point there from the repository README. How would you feel about that? Having a website seems more useful, as the docs could have several pages (intro, examples, setup, etc as other libraries) instead of having a single file.

I'll happily submit a PR for the README if you think that's the right approach!

**Comment by dfcook** [comment]
Wholeheartedly agree with Kent's suggestion. It would also need a PR against the docs to update the instructions now we've moved to scoped packages (+ maybe an example for cleanup-after-each?)

**Comment by afontcu** [comment]
Great! (Official docs have already been updated to fix the naming 😄  [Source](https://github.com/testing-library/testing-library-docs/pull/125))

So I'll submit a PR to remove docs from `README` and point readers to the official site.



I've seen that React Testing Library, ReasonReact, and Native all have like sections with several pages:

<img width="216" alt="imatge" src="https://user-images.githubusercontent.com/9197791/58750437-c2373380-8492-11e9-82ca-f71150b2a92d.png">

Wouldn't it be cool to have a similar structure for Vue?

**Comment by dfcook** [comment]
It would, happy for you to create this if you have the inclination

**Comment by afontcu** [comment]
Sure! I'll first update this repo README so we can close this up, and then think about a simple structure for docs in the official docs repo :)

**Comment by alexkrolick** [comment]
Please do! The other wrapper libs are a great starting point for structure.
