### ISSUE TITLE
Shallow Render?

### ISSUE THREAD

**Issue by gchenglevi** [testing-library/vue-testing-library#45]
Most of the time when testing with `vue-test-utils` I would be using a shallow mount. Although I know you can manually stub the components out, the method I think is quite helpful. In addition to `render` Is it possible that perhaps a `shallowRender` or something equivalent can be exposed to be used?

**Comment by afontcu** [comment]
Hi and thank you for your comment!

Vue Testing Library does not provide a shallow method on purpose. Following [Testing Library guiding principles](https://testing-library.com/docs/guiding-principles), we don't provide a shallow render as it is a path to provide false sense of security.

If you _really_ need to mock/stub a component, you can either use Jest's mocking feature or the `stubs` key provided by @vue/test-utils (you can read more and see an example in [FAQ](https://testing-library.com/docs/vue-testing-library/faq) section).

You can read more about it here: https://kentcdodds.com/blog/why-i-never-use-shallow-rendering/


Hope it helped!
