### ISSUE TITLE
Coveralls integration is broken

### ISSUE THREAD

**Issue by afontcu** [testing-library/vue-testing-library#51]
I'mn assuming it has something to do with the relocation of the package under `testing-library` umbrella. Am I right @dfcook?

Is there anything I could do to fix it other than requesting coverall access to testing-library organization?

Thanks!

**Comment by dfcook** [comment]
It looks like testing-library uses codecov.io rather than coveralls, so it could be as simple as changing the url to:

https://codecov.io/github/testing-library/vue-testing-library

**Comment by afontcu** [comment]
I just requested to install [the Codecov app](https://github.com/apps/codecov) on VTL, we'll see how it goes :)

**Comment by dfcook** [comment]
I've enabled it, want to try a commit?

**Comment by dfcook** [comment]
Updated to use codecov, also updated badge in readme
