### ISSUE TITLE
Cannot access router/history for assertions in test.

### ISSUE THREAD

**Issue by brennj** [testing-library/vue-testing-library#52]
## The goal

I want to be able to have access to my vue router instance post render so that I can keep track of where the current location is, so that I may do assertions about my router and ensure the current path is correct. I may also want to do manual triggers of URL changes after the component is mounted.

This could also be an extended idea for the `store`, so that I may check the internal state, or push actions to post mount. 

## The issue 

The way I tried to get around this was to capture the router in the third parameter of the `render` function, since it is returned as an argument. This is along with the store and vue instance. But this didn't seem to work without causing my test to go a bit nuts.

Heres what I would expect:

```
it('Should go home when cancel button clicked', async () => {
  const { router, getByText } = render(MyVueComponent);
  await fireEvent.click(getByText(/cancel/i));
  expect(router.currentRoute.path).toBe('/home');
})
```

**Comment by afontcu** [comment]
I'm closing this and leaving the PR open for a while, see if we can find a compelling reason to expose the `history` object

👍
