### ISSUE TITLE
VTL needs an emoji :) 

### ISSUE THREAD

**Issue by afontcu** [testing-library/vue-testing-library#67]
VTL is the only Testing Library member without an emoji of an animal :) 

Suggestions? I'd go with any of the greenish ones 🦎🐸🐊🦖

![imatge](https://user-images.githubusercontent.com/9197791/62381105-07d3b380-b54b-11e9-91e4-9461f92e052c.png)

**Comment by dfcook** [comment]
My youngest son is a big fan of lizards so I'd go for that one myself

**Comment by afontcu** [comment]
Sounds like a compelling reason to me :)
