### ISSUE TITLE
Automatically cleanup if afterEach is detected 

### ISSUE THREAD

**Issue by afontcu** [testing-library/vue-testing-library#77]
Right now, users need to call `afterEach(cleanup)` or configure Jest [to do so](https://testing-library.com/docs/vue-testing-library/setup#cleanup). This makes sure test run in isolation, but requires manual action.

---

As React Testing Library [just did](https://github.com/testing-library/react-testing-library/pull/430), we should probably automatically call `cleanup` if `afterEach` method exists.

RTL ended up offering two opt-out mechanisms (via custom import or using an env variable), but I'm not sure this is totally needed. I would keep the env variable (`VTL_SKIP_AUTO_CLEANUP`), but still have a single import point (instead of creating that "pure" version on VTL). Not a big deal, though.

So a PR (or several PRs) should:
* Automatically call `afterEach(cleanup)` if `afterEach` exists.
* Add an opt-out mechanism by using `VTL_SKIP_AUTO_CLEANUP`.
* Add tests asserting the behavior outlined above.
* Remove `cleanup` references from tests and docs.
* Replace cleanup-after-each with a warning ([reference](https://github.com/testing-library/react-testing-library/commit/8277b06c199cacb0e81597aa506151de7a71b439)).
* State that the change is a breaking change (so that we take it into account when merging!).

After that, we'd need to update [the official docs](https://github.com/testing-library/testing-library-docs/).

I'm marking this as a good first issue since details are outlined and the referenced PR from RTL makes a great starting point :)

**Comment by Oluwasetemi** [comment]
Can I just on this

**Comment by afontcu** [comment]
Sure, go for it! 😊

**Comment by Oluwasetemi** [comment]
@afontcu can you please help me clarify some things.

1. I will call `afterEach(cleanup)` in the main `vue-testing-library.js`?
2. I don't know how to check if afterEach is called in a test?

**Comment by afontcu** [comment]
Hi! Sure!

The idea is to follow React Testing Library steps, so [their Pull Request](https://github.com/testing-library/react-testing-library/pull/430) is gonna be really helpful.

1. Exactly, that's the main goal.
2. It's not about afterEach being called in a test, it's about checking if "afterEach" exists at all. Some test runners, such as Ava, do not have this function. Check the [index file](https://github.com/testing-library/react-testing-library/blob/master/src/index.js#L9) for React Testing Library.

I'd suggest going over that merged PR and trying to understand how are they handling the auto-cleanup.

**Comment by Oluwasetemi** [comment]
Currently going through the merged PR. I hope to send a PR when I get it all figure.

**Comment by afontcu** [comment]
great :) feel free to create a draft PR so we can discuss things over code.

**Comment by Oluwasetemi** [comment]
#80 have solved the first two concerns I think?

**Comment by afontcu** [comment]
@Oluwasetemi yes, looks great! :) 

Next step is testing it out, and also I would add some comments explaining the feature. Something like the following:

> "if the test runner supports `afterEach`, then we'll automatically run cleanup after each test. This ensures that tests run in isolation from each other. You can opt out of that behavior by setting VTL_SKIP_AUTO_CLEANUP env varible to 'true'."

**Comment by Oluwasetemi** [comment]
I just created 2 test files to check the auto-cleanup and the auto-cleanup-skip.

cc @dfcook @afontcu

**Comment by afontcu** [comment]
@Oluwasetemi perfect! I've added a few comments.

Next steps:

1. "Remove `cleanup` references from tests". It means that all tests provided in Vue Testing Library should not use `cleanup()` themselves.
2. "Replace cleanup-after-each with a warning". If someone is still importing `cleanup-after-each.js` after updating VTL, we should warn them that the file is deprecated and we might be removing it in future major releases. Similar to [this](https://github.com/testing-library/react-testing-library/blob/8277b06c199cacb0e81597aa506151de7a71b439/cleanup-after-each.js).

Thank you! 🤗 It's looking really good.

**Comment by Oluwasetemi** [comment]
I have updated the PR
