### ISSUE TITLE
Deprecate vue-testing-library

### ISSUE THREAD

**Issue by afontcu** [testing-library/vue-testing-library#78]
react-testing-library is [marked as deprecated](https://www.npmjs.com/package/react-testing-library), so anyone using it will receive a nice deprecation message.

I believe we should do the same thing with [vue-testing-library](https://www.npmjs.com/package/vue-testing-library) with the same message.

(I believe only @dfcook can actionate this).

**Comment by dfcook** [comment]
I have deprecated [vue-testing-library](https://www.npmjs.com/package/vue-testing-library) however the deprecation message currently only appears on the individual version pages, not the main page. Unsure why that is.

**Comment by afontcu** [comment]
I'm actually seeing the message right after entering the main page. Cache issues, maybe?

**Comment by dfcook** [comment]
Must be, I'll close then!
