### ISSUE TITLE
Add semanting release bot

### ISSUE THREAD

**Issue by afontcu** [testing-library/vue-testing-library#81]
Other Testing Library members are using https://github.com/semantic-release/semantic-release to handle their releases.

It looks great not only because of the sensible version bumping, but also for all the automated tasks it handles (notifications, formalized commits,...).

Thoughts?

**Comment by dfcook** [comment]
Would be very happy to go with this, getting the release process into CI was one of the things on my todo list.

**Comment by afontcu** [comment]
Great! `semantic-release` relies on commit messages to infer new versions, so AFAIK that would mean implementing a tool such as [commitizen](https://github.com/commitizen/cz-cli).

Not sure what are the implementation steps, but I'll open a PR so that we can see what are the main changes.
