### ISSUE TITLE
Add typescript definitions to DefinitelyTyped

### ISSUE THREAD

**Issue by weyert** [testing-library/vue-testing-library#84]
Let's add DefinitelyTyped type definitions for `vue-testing-library`

**Comment by weyert** [comment]
I will pick this up 💃

**Comment by afontcu** [comment]
By all means! thanks 🤘🏼🙌🏼

**Comment by afontcu** [comment]
For reference:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37655

**Comment by weyert** [comment]
Sweet :)
