### ISSUE TITLE
fireEvent.click() on <a> tag doesn't work

### ISSUE THREAD

**Issue by vinliao** [testing-library/vue-testing-library#99]
**Describe the bug**
Expectation: fireEvent.click() on <a> tag will change `window.location.href`, but it doesn't. This is "emulating" a user click on an external link on a Vue app.

**To Reproduce**
```
it('renders url and comment link properly', async () => {
  const fake_data = [
    { title: 'title number 1', url: 'http://title1.com' },
    { title: 'title number 2', url: 'http://title2.com' }
  ]

  const { getByText } = render(HomePage)
  const firstArticle = getByText(fake_data[0].title)
  // FIXME: this doesn't work
  await fireEvent.click(firstArticle)

  // assert the current browser url
  expect(window.location.href).toEqual(fake_data[0].url)
   
})
```

**Expected behavior**
I'm expecting the window.location.href to equal `http://title1.com`, but I got `http://localhost/` instead.

**Related information:**

- `@testing-library/vue` version: 3.0.0
- `Vue` version: 2.6.5
- `node` version: 10.16.3
- `npm` (or `yarn`) version: 6.9.0 

**Edit:** To be honest, I don't really know whether doing this kind of test is a good idea or not. It feels like I'm testing the implementation details of the a tag. I'd be grateful if anyone can correct me and point me in the right direction.

**Comment by afontcu** [comment]
Hi! And thanks for filling this in 🙌 

Is it possible that the issue is not related to Vue Testing Library but with `jsdom` itself? https://github.com/jsdom/jsdom/issues/2112 (and [here](https://remarkablemark.org/blog/2018/11/17/mock-window-location/)). It would make sense, as we don't do anything special regarding links.

Hope it helps!

**Comment by vinliao** [comment]
Thanks for helping @afontcu, I decided not to implement this test because simulating a click and on `<a>` tag and checking the url of the browser seems like testing the implementation details of `<a>` tag, which _I think_ is against the guiding principle.

But for the future people who encounter this problem and would like to implement this kind of test, [here's](https://stackoverflow.com/questions/54021037/how-to-mock-window-location-href-with-jest-vuejs/54034379#54034379) the best resource that I found.
